package model;

public enum Animations {

    JOUEUR_WALK_RIGHT,
    JOUEUR_WALK_LEFT,
    JOUEUR_WALK_UP,
    JOUEUR_WALK_DOWN,
    MONSTRE_WALK_RIGHT,
    MONSTRE_WALK_LEFT,
    MONSTRE_WALK_UP,
    MONSTRE_WALK_DOWN,
    FANTOME_WALK_RIGHT,
    FANTOME_WALK_LEFT,
    FANTOME_WALK_UP,
    FANTOME_WALK_DOWN
}
